"use client";

import { useEffect, useState } from "react";
import { Icon } from "../Icon";
import { formatCents, formatCentsWhole } from "@/lib/format";
import { getPerformance, type PerformanceRow } from "@/lib/hr";

/**
 * Labor-spend performance matrix. For each employee it maps attendance hours
 * against the register: sales generated by their cashier login, sales per worked
 * hour, throughput, and cash-drawer accuracy — the figures a store owner uses to
 * see where labor pays off. Register columns are blank for staff not linked to a
 * login. (True shift punctuality needs scheduled start times, which the
 * attendance model doesn't yet carry — "Attend." is the honest reliability read.)
 */
type Period = "30d" | "month" | "lastMonth";

function rangeFor(period: Period): { from: string; to: string } {
  const iso = (d: Date) => d.toISOString().slice(0, 10);
  const now = new Date();
  if (period === "month") {
    return { from: iso(new Date(now.getFullYear(), now.getMonth(), 1)), to: iso(now) };
  }
  if (period === "lastMonth") {
    return { from: iso(new Date(now.getFullYear(), now.getMonth() - 1, 1)), to: iso(new Date(now.getFullYear(), now.getMonth(), 0)) };
  }
  return { from: iso(new Date(Date.now() - 29 * 86_400_000)), to: iso(now) };
}

const PERIOD_LABEL: Record<Period, string> = {
  "30d": "Last 30 days",
  month: "This month",
  lastMonth: "Last month",
};

type SortKey = "salesPerHourCents" | "salesCents" | "hoursWorked" | "attendanceRatePct";

type Loaded =
  | { period: Period; rows: PerformanceRow[] }
  | { period: Period; error: string };

export function PerformanceMatrix() {
  const [period, setPeriod] = useState<Period>("30d");
  const [sort, setSort] = useState<SortKey>("salesPerHourCents");
  // Sentinel pattern (matches the rest of the app): we derive `loading` from
  // whether the result we hold matches the requested period, rather than setting
  // a loading state synchronously inside the effect.
  const [result, setResult] = useState<Loaded | null>(null);

  useEffect(() => {
    let alive = true;
    const { from, to } = rangeFor(period);
    void (async () => {
      const res = await getPerformance(from, to);
      if (!alive) return;
      if (res.ok) setResult({ period, rows: res.report.rows });
      else setResult({ period, error: res.error ?? "Could not load performance." });
    })();
    return () => {
      alive = false;
    };
  }, [period]);

  const loading = !result || result.period !== period;
  const error = result && "error" in result && result.period === period ? result.error : null;
  const rows =
    result && "rows" in result && result.period === period
      ? [...result.rows].sort((a, b) => (b[sort] as number) - (a[sort] as number))
      : [];
  const totals = rows.reduce(
    (acc, r) => ({ sales: acc.sales + r.salesCents, hours: acc.hours + r.hoursWorked, txns: acc.txns + r.txnCount }),
    { sales: 0, hours: 0, txns: 0 },
  );

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          {(Object.keys(PERIOD_LABEL) as Period[]).map((p) => (
            <button
              key={p}
              type="button"
              onClick={() => setPeriod(p)}
              className={
                "text-[13px] font-semibold px-3 py-1.5 rounded-[9px] transition duration-150 " +
                (period === p ? "bg-brand-50 text-brand-700" : "text-ink-soft hover:bg-paper")
              }
            >
              {PERIOD_LABEL[p]}
            </button>
          ))}
        </div>
        <label className="flex items-center gap-2 text-[12.5px] font-semibold text-ink-soft">
          Sort by
          <select value={sort} onChange={(e) => setSort(e.target.value as SortKey)} className="field-input rounded-[9px] px-2.5 py-1.5 text-[13px]">
            <option value="salesPerHourCents">Sales / hour</option>
            <option value="salesCents">Sales generated</option>
            <option value="hoursWorked">Hours worked</option>
            <option value="attendanceRatePct">Attendance</option>
          </select>
        </label>
      </div>

      {loading && <div className="rounded-xl2 bg-surface hairline shadow-card h-[320px] animate-pulse" />}
      {!loading && error && (
        <div className="rounded-xl2 bg-surface hairline shadow-card p-8 text-center">
          <p className="text-[14px] font-semibold text-rose-600">{error}</p>
        </div>
      )}

      {!loading && !error && (
        <div className="rounded-xl2 bg-surface hairline shadow-card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-[13px]">
              <thead>
                <tr className="text-left text-[11.5px] font-semibold text-ink-faint border-b border-ink/8 bg-paper/40">
                  <th className="px-5 py-2.5">Employee</th>
                  <th className="px-3 py-2.5 text-right">Hours <span className="font-normal">(reg/OT)</span></th>
                  <th className="px-3 py-2.5 text-right">Attend.</th>
                  <th className="px-3 py-2.5 text-right">Sales</th>
                  <th className="px-3 py-2.5 text-right">Sales/hr</th>
                  <th className="px-3 py-2.5 text-center">Txns</th>
                  <th className="px-5 py-2.5 text-right">Drawer acc.</th>
                </tr>
              </thead>
              <tbody>
                {rows.length === 0 && (
                  <tr>
                    <td colSpan={7} className="px-5 py-12 text-center text-[13px] text-ink-soft">
                      No employees to analyse in this period.
                    </td>
                  </tr>
                )}
                {rows.map((r) => (
                  <tr key={r.employeeId} className="border-b border-ink/5 last:border-0 hover:bg-paper/40 transition">
                    <td className="px-5 py-3">
                      <span className="font-semibold">{r.name}</span>
                      <span className="block text-[11.5px] text-ink-faint">
                        {r.position ?? "—"}
                        {!r.linked && <span className="ml-1.5 text-amber-600">· no register link</span>}
                      </span>
                    </td>
                    <td className="px-3 py-3 text-right tabular-nums whitespace-nowrap">
                      {r.hoursWorked}h
                      <span className="text-ink-faint text-[11.5px]"> · {r.regularHours}/{r.overtimeHours}</span>
                    </td>
                    <td className="px-3 py-3 text-right tabular-nums">
                      <AttendancePill pct={r.attendanceRatePct} present={r.daysPresent} />
                    </td>
                    <td className="px-3 py-3 text-right tabular-nums whitespace-nowrap font-semibold">
                      {r.linked ? formatCentsWhole(r.salesCents) : <span className="text-ink-faint">—</span>}
                    </td>
                    <td className="px-3 py-3 text-right tabular-nums whitespace-nowrap">
                      {r.linked && r.hoursWorked > 0 ? formatCents(r.salesPerHourCents) : <span className="text-ink-faint">—</span>}
                    </td>
                    <td className="px-3 py-3 text-center tabular-nums">{r.linked ? r.txnCount : <span className="text-ink-faint">—</span>}</td>
                    <td className="px-5 py-3 text-right">
                      <DrawerPill pct={r.drawerAccuracyPct} varianceCents={r.drawerVarianceCents} shifts={r.shiftsClosed} />
                    </td>
                  </tr>
                ))}
              </tbody>
              {rows.length > 0 && (
                <tfoot>
                  <tr className="border-t border-ink/10 bg-paper/40 text-[12.5px] font-bold">
                    <td className="px-5 py-2.5">Total</td>
                    <td className="px-3 py-2.5 text-right tabular-nums">{Math.round(totals.hours * 10) / 10}h</td>
                    <td className="px-3 py-2.5" />
                    <td className="px-3 py-2.5 text-right tabular-nums whitespace-nowrap">{formatCentsWhole(totals.sales)}</td>
                    <td className="px-3 py-2.5 text-right tabular-nums whitespace-nowrap">
                      {totals.hours > 0 ? formatCents(Math.round(totals.sales / totals.hours)) : "—"}
                    </td>
                    <td className="px-3 py-2.5 text-center tabular-nums">{totals.txns}</td>
                    <td className="px-5 py-2.5" />
                  </tr>
                </tfoot>
              )}
            </table>
          </div>
        </div>
      )}

      <p className="text-[11.5px] text-ink-faint flex items-start gap-1.5 max-w-[70ch]">
        <Icon name="shield" className="w-3.5 h-3.5 mt-0.5 shrink-0" strokeWidth={1.7} />
        Sales &amp; drawer figures come from each employee&rsquo;s linked cashier login. &ldquo;Attend.&rdquo; is the share of
        scheduled days worked (approved leave excluded); &ldquo;Drawer acc.&rdquo; is 100% when every closed shift balanced.
      </p>
    </div>
  );
}

function AttendancePill({ pct, present }: { pct: number; present: number }) {
  const tone = pct >= 95 ? "text-accent-600" : pct >= 80 ? "text-amber-600" : "text-rose-600";
  return (
    <span className="whitespace-nowrap">
      <span className={"font-bold " + tone}>{pct}%</span>
      <span className="text-ink-faint text-[11.5px]"> · {present}d</span>
    </span>
  );
}

function DrawerPill({ pct, varianceCents, shifts }: { pct: number | null; varianceCents: number; shifts: number }) {
  if (pct === null) return <span className="text-ink-faint text-[12px]">no shifts</span>;
  const tone = pct >= 99 ? "bg-accent-50 text-accent-600" : pct >= 95 ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-600";
  const sign = varianceCents > 0 ? "+" : "";
  return (
    <span className="inline-flex flex-col items-end">
      <span className={"inline-block text-[11px] font-bold rounded-full px-2.5 py-0.5 " + tone}>{pct}%</span>
      {varianceCents !== 0 && (
        <span className="text-[11px] text-ink-faint tabular-nums mt-0.5">
          {sign}
          {formatCents(varianceCents)} · {shifts} shift{shifts > 1 ? "s" : ""}
        </span>
      )}
    </span>
  );
}
